### PR TITLE
Update sendPost, log responses and run URL

### PR DESCRIPTION
**Pull request by rosswhitfield**

### CODE REVIEW

**Comment by elwasif** [comment]
I'm getting an error when I try to run using this PR branch 
`2022-09-23 13:21:22,913 FWK_COMP_PortalBridge_7 ERROR    Portal Error: 500 <!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

PORTAL_RUNID  =  ABC_sim_karnak_eiw_2022-09-23T13:21:22.387
`

**Comment by rosswhitfield** [comment]
> I'm getting an error when I try to run using this PR branch `2022-09-23 13:21:22,913 FWK_COMP_PortalBridge_7 ERROR Portal Error: 500 <!doctype html>
> <title>500 Internal Server Error</title>
> # Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
> 
> PORTAL_RUNID = ABC_sim_karnak_eiw_2022-09-23T13:21:22.387 `

This requires changes to the IPS-portal before it will work, I am going to wait until I have those changes in place before I merge this.

**Comment by rosswhitfield** [comment]
@elwasif Try again, I deployed the changes to the IPS-portal and this should work now.

**Comment by elwasif** [comment]
This seems to work now, seeing  3 Seconds lag at the end of the run

**Pull request merged**
